# Generated by Django 5.0.1 on 2024-05-20 22:19

import GymMembershipsApp.users.validators
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bg', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bg', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(1, '1 month'), (3, '3 months'), (6, '6 months'), (12, '12 months')])),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 21))])),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bg', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('price_for_one_month', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_for_three_months', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_for_six_months', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_for_twelve_months', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bg', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product_picture', models.ImageField(upload_to='product_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_bg', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), GymMembershipsApp.users.validators.validate_name_contains_alphabet_only])),
                ('first_name_en', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), GymMembershipsApp.users.validators.validate_name_contains_alphabet_only])),
                ('last_name_bg', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), GymMembershipsApp.users.validators.validate_name_contains_alphabet_only])),
                ('last_name_en', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), GymMembershipsApp.users.validators.validate_name_contains_alphabet_only])),
                ('trainer_type', models.CharField(choices=[('bodybuilding', 'Bodybuilding'), ('strength training', 'Strength training'), ('calisthenics', 'Calisthenics'), ('cardio', 'Cardio'), ('crossfit', 'Crossfit')], max_length=20)),
                ('trainer_picture', models.ImageField(upload_to='trainer_pictures/')),
            ],
        ),
    ]
