# Generated by Django 5.0.1 on 2024-01-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='username',
        ),
    ]
