# Generated by Django 5.0.1 on 2024-05-23 18:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 месец'), (3, '3 месеца'), (6, '6 месеца'), (12, '12 месеца')]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 5, 23))]),
        ),
    ]
