# Generated by Django 5.0.1 on 2024-03-17 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_pictures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_picture',
            field=models.ImageField(upload_to='trainer_pictures/'),
        ),
    ]
