# Generated by Django 5.0.1 on 2024-02-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price_for_one_month', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_for_three_months', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_for_six_months', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_for_twelve_months', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.membershiptype'),
        ),
    ]
