# Generated by Django 5.0.1 on 2024-02-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_membershiptype_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptype',
            name='display_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
