# Generated by Django 5.0.1 on 2024-12-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_membership_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
