# Generated by Django 5.0.1 on 2024-03-10 20:21

import GymMembershipsApp.users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_gymuser_managers_gymuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='phone_number',
            field=models.CharField(default='0898825282', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +359 or 0 followed by 9 digits.', regex='^\\+359\\d{10}$'), django.core.validators.RegexValidator(message='Phone number must start with +359 or 0 followed by 9 digits.', regex='^0\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), GymMembershipsApp.users.validators.validate_name_contains_alphabet_only]),
        ),
        migrations.AlterField(
            model_name='gymuser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), GymMembershipsApp.users.validators.validate_name_contains_alphabet_only]),
        ),
    ]
