# Generated by Django 5.0.1 on 2024-03-13 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gymuser_phone_number_alter_gymuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +359 or 0 followed by 9 digits.', regex='^(?:\\+359|0)\\d{9}$')]),
        ),
    ]
